import json

with open("public/countries.json", "r") as f:
    data = json.load(f)

existing = set(c["isoCode"] for c in data)

# Round 2: 17 more countries to reach 85
NEW = [
    {"isoCode": "lk", "countryEn": "Sri Lanka", "countryZh": "斯里兰卡", "agencyEn": "Ministry of Environment", "agencyZh": "环境部", "website": "https://www.env.gov.lk/", "region": "Asia", "descriptionEn": "Sri Lanka's ministry manages biodiversity hotspot protection and climate adaptation for this island nation.", "descriptionZh": "斯里兰卡环境部管理生物多样性热点保护和岛屿国家的气候适应。", "established": 1990, "responsibilities": ["biodiversity", "water"], "epiScore": 29.5, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "国家环境法", "nameEn": "National Environmental Act", "year": 1980}], "data": {"forestCoverage": 29, "carbonEmission": 25}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2016-09-21", "ndcTargetZh": "2030年排放比基准情景减少14.5%（无条件）", "ndcTargetEn": "Reduce GHG 14.5% below BAU by 2030 (unconditional)", "ndcRating": "2C", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2021}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1989-12-15", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1994-03-23", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳定价研究阶段", "noteEn": "Carbon pricing under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "np", "countryEn": "Nepal", "countryZh": "尼泊尔", "agencyEn": "Ministry of Forests and Environment", "agencyZh": "森林与环境部", "website": "https://mofe.gov.np/", "region": "Asia", "descriptionEn": "Nepal's ministry manages Himalayan ecosystem conservation and glacial lake outburst flood risks.", "descriptionZh": "尼泊尔森林与环境部管理喜马拉雅生态保护和冰湖溃决洪水风险。", "established": 2018, "responsibilities": ["forest", "climate"], "epiScore": 25.8, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境保护法", "nameEn": "Environment Protection Act", "year": 2019}], "data": {"forestCoverage": 25, "carbonEmission": 12}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2016-10-05", "ndcTargetZh": "2030年排放比基准情景减少23.7%（有条件）", "ndcTargetEn": "Reduce GHG 23.7% below BAU by 2030 (conditional)", "ndcRating": "1.5C", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2020}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1994-07-06", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1993-11-23", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋；保护珠峰地区生态", "commitmentEn": "Committed to 30x30; protecting Everest region ecosystems"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳市场研究阶段", "noteEn": "Carbon market under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 2, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "mm", "countryEn": "Myanmar", "countryZh": "缅甸", "agencyEn": "Ministry of Natural Resources and Environmental Conservation", "agencyZh": "自然资源与环境保护部", "website": "https://www.monrec.gov.mm/", "region": "Asia", "descriptionEn": "Myanmar's ministry manages rich teak forests and biodiversity along the Indo-Burma hotspot.", "descriptionZh": "缅甸自然资源部管理丰富的柚木森林和印度-缅甸生物多样性热点。", "established": 2016, "responsibilities": ["forest", "biodiversity"], "epiScore": 24.0, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境保护法", "nameEn": "Environmental Conservation Law", "year": 2012}], "data": {"forestCoverage": 42, "carbonEmission": 30}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2017-09-19", "ndcTargetZh": "减少林业部门碳排放，提高可再生能源至37%", "ndcTargetEn": "Reduce forestry emissions; increase renewable energy to 37%", "ndcRating": "critically_insufficient", "ndcHistory": [{"version": "INDC", "year": 2015}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1993-11-24", "kigaliAmendment": False, "commitmentZh": "已淘汰CFCs；基加利修正案尚未批准", "commitmentEn": "Phased out CFCs; Kigali Amendment not yet ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1994-11-25", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "无碳定价机制", "noteEn": "No carbon pricing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 1, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES"]},
    {"isoCode": "kh", "countryEn": "Cambodia", "countryZh": "柬埔寨", "agencyEn": "Ministry of Environment", "agencyZh": "环境部", "website": "https://www.moe.gov.kh/", "region": "Asia", "descriptionEn": "Cambodia's ministry manages Tonle Sap Lake and Mekong River conservation with focus on deforestation prevention.", "descriptionZh": "柬埔寨环境部管理洞里萨湖和湄公河保护，重点防治森林砍伐。", "established": 1993, "responsibilities": ["forest", "water"], "epiScore": 26.3, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境保护与自然资源管理法", "nameEn": "Environmental Protection and Natural Resources Management Law", "year": 1996}], "data": {"forestCoverage": 46, "carbonEmission": 15}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2017-02-06", "ndcTargetZh": "2030年排放比基准情景减少42%（有条件）", "ndcTargetEn": "Reduce GHG 42% below BAU by 2030 (conditional)", "ndcRating": "almost_sufficient", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2020}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "2001-06-27", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1995-02-09", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳信用市场发展中", "noteEn": "Carbon credit market developing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 2, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "mn", "countryEn": "Mongolia", "countryZh": "蒙古国", "agencyEn": "Ministry of Environment and Tourism", "agencyZh": "环境与旅游部", "website": "https://www.met.gov.mn/", "region": "Asia", "descriptionEn": "Mongolia's ministry manages vast steppe grasslands and combats severe desertification from overgrazing and climate change.", "descriptionZh": "蒙古国环境部管理广袤的草原草地，应对过度放牧和气候变化造成的严重荒漠化。", "established": 2012, "responsibilities": ["biodiversity", "climate"], "epiScore": 30.5, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境保护法", "nameEn": "Environmental Protection Law", "year": 2012}], "data": {"forestCoverage": 8, "carbonEmission": 35}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2016-09-21", "ndcTargetZh": "2030年排放比基准情景减少22.7%", "ndcTargetEn": "Reduce GHG 22.7% below BAU by 2030", "ndcRating": "2C", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2020}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1996-03-07", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1993-09-30", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳市场研究阶段", "noteEn": "Carbon market under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "UNCCD", "Ramsar Convention"]},
    {"isoCode": "uz", "countryEn": "Uzbekistan", "countryZh": "乌兹别克斯坦", "agencyEn": "Ministry of Ecology, Environmental Protection and Climate Change", "agencyZh": "生态、环境保护与气候变化部", "website": "https://eco.gov.uz/", "region": "Asia", "descriptionEn": "Uzbekistan's ministry manages the Aral Sea environmental disaster recovery and water-scarce Central Asian climate adaptation.", "descriptionZh": "乌兹别克斯坦生态部管理咸海环境灾难恢复和中亚缺水地区的气候适应。", "established": 2017, "responsibilities": ["water", "climate"], "epiScore": 31.2, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境保护法", "nameEn": "Environmental Protection Law", "year": 1992}], "data": {"forestCoverage": 8, "carbonEmission": 120}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2018-11-09", "ndcTargetZh": "2030年人均排放比2010年降低35%", "ndcTargetEn": "Reduce per capita GHG 35% below 2010 by 2030", "ndcRating": "not_assessed", "ndcHistory": [{"version": "INDC", "year": 2017}, {"version": "Updated NDC", "year": 2021}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1993-05-18", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1995-10-19", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳市场机制研究阶段", "noteEn": "Carbon market under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "UNCCD"]},
    {"isoCode": "ao", "countryEn": "Angola", "countryZh": "安哥拉", "agencyEn": "Ministry of the Environment", "agencyZh": "环境部", "website": "https://www.minamb.gov.ao/", "region": "Africa", "descriptionEn": "Angola's ministry manages rich biodiversity and oil-dependent economy's environmental transition.", "descriptionZh": "安哥拉环境部管理丰富的生物多样性和石油依赖经济的环境转型。", "established": 1998, "responsibilities": ["biodiversity", "water"], "epiScore": 23.5, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境基本法", "nameEn": "Environmental Base Law", "year": 1998}], "data": {"forestCoverage": 46, "carbonEmission": 35}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2020-11-10", "ndcTargetZh": "2025年排放比基准情景减少35%（有条件）", "ndcTargetEn": "Reduce GHG 35% below BAU by 2025 (conditional)", "ndcRating": "not_assessed", "ndcHistory": [{"version": "NDC", "year": 2020}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "2000-03-17", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1998-04-01", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "无碳定价机制", "noteEn": "No carbon pricing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 1, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "UNCCD"]},
    {"isoCode": "mz", "countryEn": "Mozambique", "countryZh": "莫桑比克", "agencyEn": "Ministry of Land and Environment", "agencyZh": "土地与环境部", "website": "https://www.mta.gov.mz/", "region": "Africa", "descriptionEn": "Mozambique's ministry manages coastal ecosystem protection and climate adaptation for one of Africa's most vulnerable nations.", "descriptionZh": "莫桑比克土地部管理沿海生态保护和非洲最脆弱国家之一的气候适应。", "established": 2015, "responsibilities": ["climate", "water"], "epiScore": 22.8, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境法", "nameEn": "Environment Law", "year": 1997}], "data": {"forestCoverage": 36, "carbonEmission": 10}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2018-06-04", "ndcTargetZh": "2030年排放比基准情景减少40%（有条件）", "ndcTargetEn": "Reduce GHG 40% below BAU by 2030 (conditional)", "ndcRating": "2C", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2021}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1994-09-09", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1995-08-25", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳市场研究阶段", "noteEn": "Carbon market under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 2, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "UNCCD", "Ramsar Convention"]},
    {"isoCode": "ve", "countryEn": "Venezuela", "countryZh": "委内瑞拉", "agencyEn": "Ministry of Ecosocialism", "agencyZh": "生态社会主义部", "website": "https://www.minec.gob.ve/", "region": "South America", "descriptionEn": "Venezuela's ministry manages rich biodiversity including the Amazon, Orinoco Delta, and tepui ecosystems.", "descriptionZh": "委内瑞拉生态部管理丰富的生物多样性，包括亚马逊、奥里诺科三角洲和台地生态系统。", "established": 2014, "responsibilities": ["biodiversity", "forest"], "epiScore": 31.5, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境基本法", "nameEn": "Organic Environmental Law", "year": 2006}], "data": {"forestCoverage": 52, "carbonEmission": 120}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2017-07-21", "ndcTargetZh": "2030年排放比基准情景减少20%", "ndcTargetEn": "Reduce GHG 20% below BAU by 2030", "ndcRating": "highly_insufficient", "ndcHistory": [{"version": "NDC", "year": 2017}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1989-02-06", "kigaliAmendment": False, "commitmentZh": "已淘汰CFCs；基加利修正案尚未批准", "commitmentEn": "Phased out CFCs; Kigali Amendment not yet ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1994-09-13", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "无碳定价机制", "noteEn": "No carbon pricing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 2, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "bo", "countryEn": "Bolivia", "countryZh": "玻利维亚", "agencyEn": "Ministry of the Environment and Water", "agencyZh": "环境与水资源部", "website": "https://www.mmaya.gob.bo/", "region": "South America", "descriptionEn": "Bolivia's ministry manages Andean and Amazon ecosystems with a unique 'Mother Earth' legal framework.", "descriptionZh": "玻利维亚环境部管理安第斯和亚马逊生态系统，拥有独特的「地球母亲」法律框架。", "established": 2009, "responsibilities": ["water", "biodiversity"], "epiScore": 32.5, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "地球母亲权利法", "nameEn": "Law of the Rights of Mother Earth", "year": 2010}], "data": {"forestCoverage": 50, "carbonEmission": 25}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2016-10-05", "ndcTargetZh": "2030年前保持森林碳汇并增加可再生能源", "ndcTargetEn": "Maintain forest carbon sinks and increase renewable energy by 2030", "ndcRating": "highly_insufficient", "ndcHistory": [{"version": "INDC", "year": 2015}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1994-10-03", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1994-10-03", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "无碳定价机制", "noteEn": "No carbon pricing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "cu", "countryEn": "Cuba", "countryZh": "古巴", "agencyEn": "Ministry of Science, Technology and the Environment (CITMA)", "agencyZh": "科学、技术与环境部", "website": "https://www.citma.gob.cu/", "region": "North America", "descriptionEn": "Cuba's CITMA manages Caribbean biodiversity conservation and climate adaptation with world-leading disaster preparedness.", "descriptionZh": "古巴科技环境部管理加勒比生物多样性保护和世界领先的灾害防备体系。", "established": 1994, "responsibilities": ["biodiversity", "climate"], "epiScore": 37.4, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境法", "nameEn": "Environmental Law", "year": 1997}, {"nameZh": "气候变化应对计划", "nameEn": "Plan for Climate Change (Tarea Vida)", "year": 2017}], "data": {"forestCoverage": 32, "carbonEmission": 30}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2017-01-28", "ndcTargetZh": "提高可再生能源至24%并保护沿海生态", "ndcTargetEn": "Increase renewable energy to 24% and protect coastal ecosystems", "ndcRating": "not_assessed", "ndcHistory": [{"version": "NDC", "year": 2017}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1992-07-14", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1994-03-08", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "无碳定价机制", "noteEn": "No carbon pricing"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES", "Ramsar Convention"]},
    {"isoCode": "do", "countryEn": "Dominican Republic", "countryZh": "多米尼加", "agencyEn": "Ministry of the Environment and Natural Resources", "agencyZh": "环境与自然资源部", "website": "https://ambiente.gob.do/", "region": "North America", "descriptionEn": "Dominican Republic's ministry manages Caribbean island biodiversity and coral reef conservation.", "descriptionZh": "多米尼加环境部管理加勒比岛屿生物多样性和珊瑚礁保护。", "established": 2000, "responsibilities": ["biodiversity", "water"], "epiScore": 32.8, "netZeroTarget": 2050, "keyLaws": [{"nameZh": "环境与自然资源总法", "nameEn": "General Law on the Environment and Natural Resources", "year": 2000}], "data": {"forestCoverage": 41, "carbonEmission": 25}, "parisAgreement": {"status": "ratified", "ratifiedDate": "2017-09-21", "ndcTargetZh": "2030年排放比基准情景减少27%", "ndcTargetEn": "Reduce GHG 27% below BAU by 2030", "ndcRating": "insufficient", "ndcHistory": [{"version": "INDC", "year": 2015}, {"version": "Updated NDC", "year": 2020}], "nextNdcDeadline": 2025}, "montrealProtocol": {"status": "ratified", "ratifiedDate": "1993-03-18", "kigaliAmendment": True, "commitmentZh": "已淘汰CFCs；基加利修正案已批准", "commitmentEn": "Phased out CFCs; Kigali Amendment ratified"}, "cbd": {"status": "ratified", "ratifiedDate": "1996-11-25", "target30x30": 30, "commitmentZh": "承诺2030年保护30%陆地和海洋", "commitmentEn": "Committed to 30x30 target"}, "carbonPricing": {"hasETS": False, "hasCarbonTax": False, "priceUSD": None, "coveragePercent": 0, "noteZh": "碳市场研究阶段", "noteEn": "Carbon market under study"}, "reportingStatus": {"btrSubmitted": False, "btrYear": None, "nationalComm": 3, "statusZh": "BTR1待提交", "statusEn": "BTR1 pending"}, "treaties": ["Paris Agreement", "CBD", "CITES"]},
]

added = 0
for c in NEW:
    if c["isoCode"] in existing:
        print(f"Skip {c['isoCode']}")
        continue
    c["flagUrl"] = f"https://flagcdn.com/{c['isoCode']}.svg"
    c["contact"] = {"email": ""}
    data.append(c)
    existing.add(c["isoCode"])
    added += 1

with open("public/countries.json", "w") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

from collections import Counter
regions = Counter(c["region"] for c in data)
print(f"\nAdded {added}. Total: {len(data)}")
for r, n in regions.most_common():
    print(f"  {r}: {n}")
